        jQuery(function() {
            jQuery("#lbg_audio6_html5_shoutcast_1").audio6_html5({
              radio_stream:"http://142.4.216.91:8090/",
                  radio_name:"RadioLatinotx",
              playerWidth:355,
              imageHeight:355,
              skin:"blackControllers",
              responsive:true,
              grabLastFmPhoto:true,
              autoPlay:true,
              songTitleColor:"#000",
              authorTitleColor:"#000000",
              lineSeparatorColor:"#7A7A7A",
              radioStationColor:"#fff",
              frameBehindTextColor:"#ffffff",
              frameBehindButtonsColor:"#000000",
              sticky:false,
              startMinified:false,
              showOnlyPlayButton:false,
              centerPlayer:true,
              playerBorderSize:0,
              playerBorderColor:"#000000",
              showFacebookBut:false,
              facebookAppID:"",
              facebookShareTitle:"HTML5 Radio Player With History - Shoutcast and Icecast",
              facebookShareDescription:"A top-notch responsive HTML5 Radio Player compatible with all major browsers and mobile devices.",
              showTwitterBut:false,
              showVolume:true,
              showRadioStation:true,
              showTitle:true,
              showHistoryBut:true,
              showHistory:false,
              showHistoryOnInit:true,
              translateReadingData:"reading data...",
              historyTranslate:"HISTORIAL MUSICAL",            
              offlineText: 'RADIO EL LATINO TX', 
              playedText: 'Sonando', 
              unknownTrackText: 'RADIO EL LATINO TX',
              unknownArtistText: 'LIVE RADIO',
              historyTitleColor:"#858585",
              historyBgColor:"#f0f0f0",
              historyRecordBgColor:"transparent",
              historyRecordBottomBorderColor:"transparent",
              historyRecordSongColor:"#000000",
              historyRecordSongBottomBorderColor:"#818181",
              historyRecordAuthorColor:"#6d6d6d",
              numberOfThumbsPerScreen:3,
              historyPadding:16,
              historyRecordTitleLimit:25,
              historyRecordAuthorLimit:36,
              nowPlayingInterval:15,
              noImageAvailable:"http://www.radioimpactreports.com/wp-content/uploads/2016/12/On-Air-Mike-iStock-500394680-2-e1482345633686.jpg"
            });
          });